

MIDI_CH         = 0
SERIAL_SPEED    = 38400
SAMPLING_RATE   = 62500
FREQUENCY_MAX   = 7812
BIT_DEPTH       = 8
NOTE_NUMBER_MIN = 24
NOTE_NUMBER_MAX = 84

VCO_TUNE_RATE_TABLE_STEPS_BITS         = 6
VCO_TUNE_RATE_DENOMINATOR_BITS         = 16
VCO_PHASE_RESOLUTION_BITS              = 16
VCO_WAVE_TABLE_AMPLITUDE               = 96
VCO_WAVE_TABLE_SAMPLES_BITS            = 8
VCF_TABLE_FRACTION_BITS                = 14
EG_LEVEL_MAX                           = (127 << 1) << 8
EG_CONTROLLER_STEPS_BITS               = 5
EG_DECAY_RELEASE_RATE_DENOMINATOR_BITS = 8

DATA_BYTE_MAX         = 0x7F
STATUS_BYTE_INVALID   = 0x7F
DATA_BYTE_INVALID     = 0x80
STATUS_BYTE_MIN       = 0x80
NOTE_OFF              = 0x80
NOTE_ON               = 0x90
CONTROL_CHANGE        = 0xB0
SYSTEM_MESSAGE_MIN    = 0xF0
SYSTEM_EXCLUSIVE      = 0xF0
TIME_CODE             = 0xF1
SONG_POSITION         = 0xF2
SONG_SELECT           = 0xF3
TUNE_REQUEST          = 0xF6
EOX                   = 0xF7
REAL_TIME_MESSAGE_MIN = 0xF8
ACTIVE_SENSING        = 0xFE

OSC_TYPE      = 16
OSC_COLOR     = 17
MOD_FREQ      = 18
MOD_DEPTH     = 19
ENV_A         = 20
ENV_D         = 21
ENV_S         = 22
ENV_R         = 23
ALL_NOTES_OFF = 123
